# libimagequant is a pure C library.
# Rust/Cargo is entirely optional. You can also use ./configure && make
[package]
authors = ["Kornel Lesiński <kornel@pngquant.org>"]
build = "rust/build.rs"
categories = ["external-ffi-bindings"]
homepage = "https://pngquant.org/lib"
include = ["COPYRIGHT", "rust/*", "*.c", "*.h", "README.md", "Cargo.toml"]
keywords = ["pngquant"]
license = "GPL-3.0+"
links = "imagequant"
name = "imagequant-sys"
readme = "README.md"
repository = "https://github.com/ImageOptim/libimagequant"
version = "2.11.0"
description = "Statically linked C part of imagequant library powering tools such as pngquant.\n\nThis library is dual-licensed like pngquant: either GPL or a commercial license. See website for details: https://pngquant.org"

[build-dependencies]
cc = "1.0.1"

[dependencies]
rgb = "0.7"

[features]
default = ["sse"]
sse = []

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
name = "imagequant_sys"
path = "rust/libimagequant.rs"
doctest = false
